spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/coffee
    username: coffee
    password: coffee
  flyway:
    url: jdbc:postgresql://localhost:5432/coffee
    user: coffee
    password: coffee

logging.level.web: DEBUG
